# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85bcf13336fefe4ba9c7fccaf9ab2e55a9ae7c99d60f7ff79be79f18bb430f8b0c50fb0d2161582663f5087419bdb630d1598e13b9727e47dc0d47f0cedcd936

test:
  secret_key_base: ce460783dcd1f3b85f0c89f346b3c57b1bd5797ee07113e52f96cbfebbac3a489446899d1760ff99b336027386af51c33d12c8e1624bd3cd5a57d9102822f1ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 300135b3bd450cf18237344e6991778e51a4ef3b1636c6fd2c6318403af3f14af5e7997fa0de98df3ac30a1dc7896a02ccdf6130ade8bd9b83fed9376c96d4c3
