class Category < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :category_posts, dependent: :destroy

  has_many :posts, through: :category_posts

  # validations ...............................................................
  validates_presence_of :name, :handle
  validates_uniqueness_of :name, :handle

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  paginates_per 10

  # class methods .............................................................
  # public instance methods ...................................................

end
