class Category < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :category_posts, dependent: :destroy

  has_many :posts, through: :category_posts

  # validations ...............................................................
  validates_presence_of :name, :handle
  validates_uniqueness_of :name, :handle

  # callbacks .................................................................
  # scopes ....................................................................
  scope :publish_post, -> { where(posts: { post_type: 'post', status: 'publish' }) }

  # additional config .........................................................
  paginates_per 10

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

end
