class News < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  validates_presence_of :title, :posted_at, :link

  # callbacks .................................................................
  before_save do
    self.link = "http://#{self.link}" unless self.link.match(/^http/)
  end

  # scopes ....................................................................
  default_scope { order('posted_at DESC') }

  # additional config .........................................................
  paginates_per 10

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

end
