# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2']

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Set up MySQL
        env:
          DB_DATABASE: tcdfg_wp_test
          DB_USER: root
          DB_PASSWORD: vAyqm2gM5vF49fbaVkNG
          MYSQL_ROOT_PASSWORD: vAyqm2gM5vF49fbaVkNG
        run: |
          sudo /etc/init.d/mysql start
          mysql --host 127.0.0.1 -u${{ env.DB_USER }} -pvAyqm2gM5vF49fbaVkNG
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          sudo service mysql start
          bundle exec rails db:setup
      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
      - name: Run tests
        run: |
          bundle exec rails test
